
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Footer from "./Home/Components/Footer";
import Navbar from "./Home/Components/Navbar";
import SessionWrapper from "./components/SessionWrapper";
import { SessionProvider } from "next-auth/react";
import Script from "next/script";

<Script
  src="https://checkout.razorpay.com/v1/checkout.js"
  strategy="afterInteractive"
/>

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Fanfuel",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
 
      <body>
           <SessionWrapper>
      <Navbar/>
      <div className='bg-gray-100 min-h-screen w-screen justify-center'> {children} </div>
        <Footer/>
        </SessionWrapper>
      </body> 
    </html>
  );
}
